/*
    Ameer Arsala
    aarsala@calpoly.edu
*/

INSERT INTO Airports VALUES ('APG','Phillips AAF ','Aberdeen ','United States ','US ');
INSERT INTO Airports VALUES ('ABR','Municipal ','Aberdeen ','United States ','US ');
INSERT INTO Airports VALUES ('DYS','Dyess AFB ','Abilene ','United States ','US ');
INSERT INTO Airports VALUES ('ABI','Municipal ','Abilene ','United States ','US ');
INSERT INTO Airports VALUES ('VJI','Virginia Highlands ','Abingdon ','United States ','US ');
INSERT INTO Airports VALUES ('ADT','Ada ','Ada ','United States ','US ');
INSERT INTO Airports VALUES ('ADK','Adak Island Ns ','Adak Island ','United States ','US ');
INSERT INTO Airports VALUES ('ADG','Lenawee County ','Adrian ','United States ','US ');
INSERT INTO Airports VALUES ('AFO','Municipal ','Afton ','United States ','US ');
INSERT INTO Airports VALUES ('AIK','Municipal ','Aiken ','United States ','US ');
INSERT INTO Airports VALUES ('ANW','Ainsworth ','Ainsworth ','United States ','US ');
INSERT INTO Airports VALUES ('AKK','Akhiok SPB ','Akhiok ','United States ','US ');
INSERT INTO Airports VALUES ('KKI','Spb ','Akiachak ','United States ','US ');
INSERT INTO Airports VALUES ('AKI','Akiak ','Akiak ','United States ','US ');
INSERT INTO Airports VALUES ('AKO','Colorado Plains Regional Airport ','Akron CO ' ,'United States ','US ');
INSERT INTO Airports VALUES ('CAK','Akron/canton Regional ','Akron/Canton OH ' ,'United States ','US ');
INSERT INTO Airports VALUES ('AKC','Fulton International ','Akron/Canton ','United States ','US ');
INSERT INTO Airports VALUES ('KQA','Akutan ','Akutan ','United States ','US ');
INSERT INTO Airports VALUES ('AUK','Alakanuk ','Alakanuk ','United States ','US ');
INSERT INTO Airports VALUES ('NGZ','NAS ','Alameda ','United States ','US ');
INSERT INTO Airports VALUES ('HMN','Holloman AFB ','Alamogordo ','United States ','US ');
INSERT INTO Airports VALUES ('ALM','Municipal ','Alamogordo ','United States ','US ');
INSERT INTO Airports VALUES ('ALS','Municipal ','Alamosa ','United States ','US ');
INSERT INTO Airports VALUES ('NAB','Albany NAS ','Albany ','United States ','US ');
INSERT INTO Airports VALUES ('ABY','Dougherty County ','Albany ','United States ','US ');
INSERT INTO Airports VALUES ('ALB','Albany International ','Albany ','United States ','US ');
INSERT INTO Airports VALUES ('CVO','Albany ','Albany ','United States ','US ');
INSERT INTO Airports VALUES ('AEL','Albert Lea ','Albert Lea ','United States ','US ');
INSERT INTO Airports VALUES ('ABQ','Albuquerque International ','Albuquerque ','United States ','US ');
INSERT INTO Airports VALUES ('WKK','Aleknagik ','Aleknagik ','United States ','US ');
INSERT INTO Airports VALUES ('AED','Aleneva ','Aleneva ','United States ','US ');
INSERT INTO Airports VALUES ('ALX','Thomas C Russell Fld ', 'Alexander City AL ' ,'United States ','US ');
INSERT INTO Airports VALUES ('AEX','Alexandria International ', 'Alexandria LA ' ,'United States ','US ');
INSERT INTO Airports VALUES ('ESF','Esler Field ','Alexandria ','United States ','US ');
INSERT INTO Airports VALUES ('AXN','Alexandria ','Alexandria ','United States ','US ');
INSERT INTO Airports VALUES ('AXB','Alexandria Bay ','Alexandria Bay ','United States ','US ');
INSERT INTO Airports VALUES ('AXG','Algona ','Algona ','United States ','US ');
INSERT INTO Airports VALUES ('ALI','International ','Alice ','United States ','US ');
INSERT INTO Airports VALUES ('AIV','George Downer ', 'Aliceville AL ' ,'United States ','US ');
INSERT INTO Airports VALUES ('ALZ','Alitak SPB ','Alitak ','United States ','US ');
INSERT INTO Airports VALUES ('AET','Allakaket ','Allakaket ','United States ','US ');
INSERT INTO Airports VALUES ('AIA','Alliance ','Alliance ','United States ','US ');
INSERT INTO Airports VALUES ('AMN','Gratiot Community ','Alma ','United States ','US ');
INSERT INTO Airports VALUES ('APN','Alpena County Regional ','Alpena ','United States ','US ');
INSERT INTO Airports VALUES ('ALE','Alpine ','Alpine ','United States ','US ');
INSERT INTO Airports VALUES ('ALN','Alton ','Alton ','United States ','US ');
INSERT INTO Airports VALUES ('LTS','Altus AFB ','Altus ','United States ','US ');
INSERT INTO Airports VALUES ('AXS','Municipal ','Altus ','United States ','US ');
INSERT INTO Airports VALUES ('AQY','Alyeska ','Alyeska ','United States ','US ');
INSERT INTO Airports VALUES ('AMA','Rick Husband Amarillo International ', 'Amarillo  ' ,'United States ','US ');
INSERT INTO Airports VALUES ('TDW','Tradewind ','Amarillo ','United States ','US ');
INSERT INTO Airports VALUES ('ABL','Ambler ','Ambler ','United States ','US ');
INSERT INTO Airports VALUES ('AHT','Amchitka ','Amchitka ','United States ','US ');
INSERT INTO Airports VALUES ('AHH','Municipal ','Amery ','United States ','US ');
INSERT INTO Airports VALUES ('AMW','Ames ','Ames ','United States ','US ');
INSERT INTO Airports VALUES ('AYZ','Zahns ','Amityville ','United States ','US ');
INSERT INTO Airports VALUES ('AOS','Amook ','Amook ','United States ','US ');
INSERT INTO Airports VALUES ('OTS','Anacortes ','Anacortes ','United States ','US ');
INSERT INTO Airports VALUES ('NDV','USN Heliport ','Anacostia ','United States ','US ');
INSERT INTO Airports VALUES ('ANA','Orange County Steel Salvage Heliport ','Anaheim ','United States ','US ');
INSERT INTO Airports VALUES ('AKP','Anaktuvuk ','Anaktuvuk ','United States ','US ');
INSERT INTO Airports VALUES ('EDF','Elmendorf Afb ','Anchorage ','United States ','US ');
INSERT INTO Airports VALUES ('ANC','Ted Stevens Anchorage International Airport ','Anchorage ','United States ','US ');
INSERT INTO Airports VALUES ('MRI','Merrill Field ','Anchorage ','United States ','US ');
INSERT INTO Airports VALUES ('AID','Municipal ','Anderson ','United States ','US ');
INSERT INTO Airports VALUES ('AND','Anderson ','Anderson ','United States ','US ');
INSERT INTO Airports VALUES ('ADR','Andrews ','Andrews ','United States ','US ');
INSERT INTO Airports VALUES ('AXX','Angel Fire ','Angel Fire ','United States ','US ');
INSERT INTO Airports VALUES ('ANQ','Tri-State Steuben Cty ','Angola ','United States ','US ');
INSERT INTO Airports VALUES ('AGN','Angoon ','Angoon ','United States ','US ');
INSERT INTO Airports VALUES ('RFK','Rollang Field ','Anguilla ','United States ','US ');
INSERT INTO Airports VALUES ('ANI','Aniak ','Aniak ','United States ','US ');
INSERT INTO Airports VALUES ('AIB','Anita Bay ','Anita Bay ','United States ','US ');
INSERT INTO Airports VALUES ('ARB','Municipal ', 'Ann Arbor MI ' ,'United States ','US ');
INSERT INTO Airports VALUES ('ANP','Lee ','Annapolis ','United States ','US ');
INSERT INTO Airports VALUES ('ANN','Annette Island ','Annette Island ','United States ','US ');
INSERT INTO Airports VALUES ('ANB','Anniston Metropolitan ', 'Anniston AL ' ,'United States ','US ');
INSERT INTO Airports VALUES ('QAW','Ft Mcclellan Bus Trml ','Anniston ','United States ','US ');
INSERT INTO Airports VALUES ('RLI','Reilly AHP ','Anniston ','United States ','US ');
INSERT INTO Airports VALUES ('ANY','Anthony ','Anthony ','United States ','US ');
INSERT INTO Airports VALUES ('ATE','Antlers ','Antlers ','United States ','US ');
INSERT INTO Airports VALUES ('ANV','Anvik ','Anvik ','United States ','US ');
INSERT INTO Airports VALUES ('AAF','Municipal ','Apalachicola ','United States ','US ');
INSERT INTO Airports VALUES ('APV','Apple Valley ','Apple Valley ','United States ','US ');
INSERT INTO Airports VALUES ('ATW','Outagamie County ','Appleton ','United States ','US ');
INSERT INTO Airports VALUES ('AHF','Municipal ','Arapahoe ','United States ','US ');
INSERT INTO Airports VALUES ('ACV','Arcata ','Arcata ','United States ','US ');
INSERT INTO Airports VALUES ('ARC','Arctic Village ','Arctic Village ','United States ','US ');
INSERT INTO Airports VALUES ('AHD','Downtown ','Ardmore ','United States ','US ');
INSERT INTO Airports VALUES ('ADM','Ardmore Municipal Arpt ','Ardmore ','United States ','US ');
INSERT INTO Airports VALUES ('JLH','US Army Heliport ','Arlington Heights ','United States ','US ');
INSERT INTO Airports VALUES ('ATS','Artesia ','Artesia ','United States ','US ');
INSERT INTO Airports VALUES ('ARX','Asbury Park ', 'Neptune ' ,'United States ','US ');
INSERT INTO Airports VALUES ('ASX','Ashland ','Ashland ','United States ','US ');
INSERT INTO Airports VALUES ('ASY','Ashley ','Ashley ','United States ','US ');
INSERT INTO Airports VALUES ('ASE','Aspen ','Aspen ','United States ','US ');
INSERT INTO Airports VALUES ('AST','Astoria ','Astoria ','United States ','US ');
INSERT INTO Airports VALUES ('AHN','Athens ','Athens ','United States ','US ');
INSERT INTO Airports VALUES ('ATO','Ohio University ','Athens ','United States ','US ');
INSERT INTO Airports VALUES ('MMI','McMinn County ','Athens ','United States ','US ');

